### ISSUE TITLE
Use color and channel name information from metadata

### ISSUE THREAD

**Issue by jni** [tlambert03/napari-bioformats#8]
The plugin seems to load the color and channel name metadata fine from my [nd2 file](https://www.dropbox.com/s/w24jlgb24vywmat/train_TR67_Inj7_fr50.nd2?dl=0) (see screenshot below), but doesn't use them. The color is given in decimal format — I wrote a converter to RGB tuple here:

https://github.com/DragaDoncila/nd2-dask/blob/e7b07af809a291462201c04a3ad629b6d947661b/nd2_dask/nd2_reader.py#L44-L51

I pass it in as a `vispy.color.Colormap` here:

https://github.com/DragaDoncila/nd2-dask/blob/e7b07af809a291462201c04a3ad629b6d947661b/nd2_dask/nd2_reader.py#L186

<img width="295" alt="Screen Shot 2021-08-05 at 4 43 42 pm" src="https://user-images.githubusercontent.com/492549/128303797-ba545344-5f35-4934-aadd-572389a19f8a.png">

**Comment by tlambert03** [comment]
I had it using color for a while, but then removed it as it was a common source of bugs (depending on the file).  Can add back

**Comment by jni** [comment]
The color is slightly less important than the name. Without either it can be confusing.

**Comment by tlambert03** [comment]
thanks for this.  I created #12 ... let me know if it's what you were going for:

<img width="853" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/128898972-f2d10e27-afd5-4d73-9056-bc15b0804a43.png">

Also, i think there _might_ be an endianness RGBA/ABGR reversal in either your code or in the the actual number given in the metadata ... for example, in your nd2 file here, here's the output of `decimal2rgba` compared to the [`_jrgba_to_rgba` used in pims](https://github.com/soft-matter/pims/blob/68c560e72e5673da3c6fc7952c0beb4a3fb1f509/pims/bioformats.py#L110):

```python
def _jrgba_to_rgb(rgba):
    return ((rgba >> 24 & 255) / 255.,
            (rgba >> 16 & 255) / 255.,
            (rgba >> 8 & 255) / 255.,)
```

| channel name | ome number |    decimal2rgba   | _jrgba_to_rgb       |
|:------------:|:----------:|:-----------------:|----------------------|
| Alexa 488    | 16711935   | [1, 0, 1, 0] | (0, 1, 0) |
| Alexa 568    | -16776961  | [1, 0, 0, 1] | (1, 0, 0) |
| Alexa 647    | -8323073   | [1, 0, 0.5, 1] | (1, 0.5, 1) |
| Transmitted  | -1         | [1, 1, 1, 1] | (1, 1, 1) |

(the colors from the `_jrgba` column seem to match the expectations of the channel name better) 
is it possible that you need to use `'>u4'` instead?
