### ISSUE TITLE
Plugin doesn't work at all with (recent?) PySide2

### ISSUE THREAD

**Issue by jni** [tlambert03/napari-bioformats#9]
Specifically, whatever PySide2 we use in the bundle.

The error happens in this line:

https://github.com/tlambert03/napari-bioformats/blob/a030f043df654f4283c3651ff84199d65ac8113c/napari_bioformats/_downloader.py#L75

with:

```pytb
AttributeError: 'PySide2.QtCore.QEventLoop' object has no attribute 'exec'
```

I see another `.exec()` in the code base that might cause issues here:

https://github.com/tlambert03/napari-bioformats/blob/1e3add6c91c3e7e3866b233145ad530fc3887347/napari_bioformats/_dialogs.py#L73

iirc I guess the fix is to replace it with `.exec_()`?

**Comment by tlambert03** [comment]
Ahh yep, thanks
